spring:
  datasource:
    todos:
      url: jdbc:mysql://localhost:3310/local
      username: root
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver
    topics:
      url: jdbc:mysql://localhost:3307/local
      username: root
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver